# Используем официальный образ Node.js
FROM node:18

# Создаем директорию для приложения
WORKDIR /app

# Копируем yarn.lock и package.json
COPY yarn.lock package.json ./

# Устанавливаем зависимости с использованием Yarn
RUN yarn install

# Устанавливаем зависимости для разработки
RUN yarn add nodemon ts-node --dev

# Копируем исходный код
COPY . .

# Указываем порт, на котором будет работать приложение
EXPOSE 5000

# Запуск приложения в режиме разработки
CMD ["yarn", "dev"]
